# Generated by Django 3.1.7 on 2021-05-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=25)),
                ('Jobtitle', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=13)),
                ('profile', models.CharField(max_length=500)),
                ('skill1', models.CharField(max_length=50)),
                ('skill2', models.CharField(max_length=50)),
                ('skill3', models.CharField(max_length=50)),
                ('skilldesc1', models.CharField(max_length=150)),
                ('skilldesc2', models.CharField(max_length=150)),
                ('skilldesc3', models.CharField(max_length=150)),
                ('tech1', models.CharField(max_length=15)),
                ('tech2', models.CharField(max_length=15)),
                ('tech3', models.CharField(max_length=15)),
                ('tech4', models.CharField(max_length=15)),
                ('tech5', models.CharField(max_length=15)),
                ('tech6', models.CharField(max_length=15)),
                ('job1', models.CharField(max_length=15)),
                ('job2', models.CharField(max_length=15)),
                ('job3', models.CharField(max_length=15)),
                ('job4', models.CharField(max_length=15)),
                ('comname1', models.CharField(max_length=15)),
                ('comname2', models.CharField(max_length=15)),
                ('comname3', models.CharField(max_length=15)),
                ('comname4', models.CharField(max_length=15)),
                ('Upto1', models.CharField(max_length=4)),
                ('fromyear1', models.IntegerField(max_length=4)),
                ('Upto2', models.IntegerField(max_length=4)),
                ('fromyear2', models.IntegerField(max_length=4)),
                ('Upto3', models.IntegerField(max_length=4)),
                ('fromyear3', models.IntegerField(max_length=4)),
                ('Upto4', models.IntegerField(max_length=4)),
                ('fromyear4', models.IntegerField(max_length=4)),
                ('jt1', models.CharField(max_length=100)),
                ('jt2', models.CharField(max_length=100)),
                ('jt3', models.CharField(max_length=100)),
                ('jt4', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=20)),
                ('degree', models.CharField(max_length=20)),
                ('gpa', models.IntegerField(max_length=4)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
