# Generated by Django 3.1.7 on 2021-05-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_information'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='Jobtitle',
            new_name='jobtitle',
        ),
        migrations.AlterField(
            model_name='information',
            name='Upto2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='information',
            name='Upto3',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='information',
            name='Upto4',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='information',
            name='fromyear1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='information',
            name='fromyear2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='information',
            name='fromyear3',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='information',
            name='fromyear4',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='information',
            name='gpa',
            field=models.IntegerField(),
        ),
    ]
