# Generated by Django 3.1.7 on 2021-05-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_infosecond'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infosecond',
            name='lifepb1',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='infosecond',
            name='lifepb2',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='infosecond',
            name='lifepb3',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='infosecond',
            name='lifepb4',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='infosecond',
            name='pb1',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='infosecond',
            name='pb2',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='infosecond',
            name='pb3',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='infosecond',
            name='pb4',
            field=models.CharField(max_length=3),
        ),
    ]
