# Generated by Django 3.1.7 on 2021-05-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_auto_20210508_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Freshers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=25)),
                ('lastname', models.CharField(blank=True, max_length=25)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=13)),
                ('linkedin', models.CharField(max_length=12)),
                ('freshers_img', models.ImageField(upload_to='images/')),
                ('school', models.CharField(max_length=15)),
                ('Upto1', models.CharField(max_length=4)),
                ('fromyear1', models.IntegerField()),
                ('college', models.CharField(max_length=15)),
                ('Upto2', models.CharField(max_length=4)),
                ('fromyear2', models.IntegerField()),
                ('graduation', models.CharField(max_length=15)),
                ('Upto3', models.CharField(max_length=4)),
                ('fromyear3', models.IntegerField()),
                ('lang1', models.CharField(max_length=15)),
                ('lang2', models.CharField(max_length=15)),
                ('lang3', models.CharField(max_length=15)),
                ('projecttitle1', models.CharField(max_length=15)),
                ('projectskill1', models.CharField(max_length=10)),
                ('desc1', models.CharField(max_length=350)),
                ('projecttitle2', models.CharField(max_length=15)),
                ('projectskill2', models.CharField(max_length=10)),
                ('desc2', models.CharField(max_length=350)),
                ('projecttitle3', models.CharField(max_length=15)),
                ('projectskill3', models.CharField(max_length=10)),
                ('desc3', models.CharField(max_length=350)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='infosecond',
            name='firstname',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='infosecond',
            name='lastname',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
