# Generated by Django 3.1.7 on 2021-05-10 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_auto_20210509_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='freshers',
            name='address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='freshers',
            name='profile',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='freshers',
            name='tech1',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='freshers',
            name='tech2',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='freshers',
            name='tech3',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='freshers',
            name='tech4',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='freshers',
            name='tech5',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='freshers',
            name='tech6',
            field=models.CharField(default='', max_length=15),
        ),
    ]
