# Generated by Django 3.1.7 on 2021-05-10 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_auto_20210510_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freshers',
            name='freshers_img',
        ),
    ]
